#!/usr/bin/env php
<?php declare(strict_types=1);

use Sirius\CommandManager;
use Sirius\Kernel;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('SIRIUS_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('SIRIUS_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require SIRIUS_COMPOSER_INSTALL;

if (php_sapi_name() == 'cli') {

    isset($argv[1]) ? $commandName = $argv[1]:$commandName = Sirius\CommandManager::HELP_ARGUMENT;
    $arguments = [];
    foreach ($argv as $key => $arg) {
        if ($key < 2) {
            continue;
        }

        $arguments[] = $arg;
    }

    $kernel = new Kernel();
    $commandManager = new CommandManager($kernel);
    $commandManager->main($commandName, $arguments);
}
